### ISSUE TITLE
Dynmap, Bluemap, squaremap Support?

### ISSUE THREAD

**Issue by MrRagtime** [lofi-enjoyer/NubladaTowns#49]
Please, this would be a nice feature to add!
- https://github.com/BlueMap-Minecraft/BlueMapAPI
- https://github.com/webbukkit/dynmap/wiki/Dynmap-API
- https://github.com/jpenilla/squaremap/wiki/API-Dependency-Information  /  https://github.com/jpenilla/squaremap/wiki/API-Basics

**Comment by lofi-enjoyer** [comment]
I started working on a squaremap integration a while ago and left it incomplete. I'll try to finish it before the next release, thanks for the suggestion!
