### ISSUE TITLE
[BUG] After changed flag and can't be expanded territory

### ISSUE THREAD

**Issue by DrJekyllH** [lofi-enjoyer/NubladaTowns#50]
After establishing a town, the flag is changed and the territory cannot be expanded with the changed flag.

**Comment by lofi-enjoyer** [comment]
I cannot reproduce the bug. Is there any error in chat or console? Did you rename the new banner with the name of the city before claiming?

**Comment by DrJekyllH** [comment]
```
Did you rename the new banner with the name of the city before claiming?
```
Oh, ok.
I see that the banner's name needs to match the name of the city. That is indeed true.
As for copying the banner, the easiest way is to copy the original banner on the workbench, but another way is to make a banner of the same color and shape and rename it to the name of the city.
I have checked and it works fine. My apologies.

**Comment by lofi-enjoyer** [comment]
No problem!
